### ISSUE TITLE
Idea: button to show console logs

### ISSUE THREAD

**Issue by FabioRosado** [anaconda/pyscript-hackathon#11]
When stuff goes wrong or when exploring things I keep opening the consol e log to see whats happening. Perhaps we could add a tab to show logs directly? mind you I don't know if you can even proxy the console logs into a page

**Comment by antocuni** [comment]
my fundamental idea for pyscript is that by default, everything should go "on the page", specifically to avoid what you describe (e.g., in mobile accessing the console is hard/impossible?).

**Comment by FabioRosado** [comment]
Closing this issue, this seems like something the OSS side should do and we already do a great deal of showing an error when things go wrong
